"""Automatic, low-risk skill evolution loop.

This module is intentionally self-contained so the plugin can improve skills
without patching Hermes core. The safe mutation policy is append-only: generate a
managed evidence-backed section, preserve the existing skill text, then apply via
hash/backup/verification guardrails.
"""

from __future__ import annotations

import json
import os
import re
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .guarded_apply import apply_guarded_patch, sha256_file
from .reports import build_report
from .storage import EvidenceStore

_START = "<!-- curator-evolver:auto:start -->"
_END = "<!-- curator-evolver:auto:end -->"
_FRONTMATTER_NAME_RE = re.compile(r"^---\s*\n(?P<body>.*?)\n---\s*\n", re.DOTALL)
_NAME_RE = re.compile(r"^name:\s*[\"']?(?P<name>[^\"'\n]+)[\"']?\s*$", re.MULTILINE)


@dataclass(frozen=True)
class AutoEvolveConfig:
    """Configuration for one automatic evolution pass."""

    db_path: str | Path | None = None
    skills_dir: str | Path | None = None
    backup_dir: str | Path | None = None
    days: int = 7
    max_skills: int = 3
    min_evidence: int = 2
    apply_low_risk: bool = False
    approve_auto_apply: bool = False
    verify_command: str | None = None
    verify_cwd: str | Path | None = None


def _default_skills_dir() -> Path:
    return Path.home() / ".hermes" / "skills"


def _default_backup_dir() -> Path:
    return Path.home() / ".hermes" / "plugins" / "curator-evolver" / "backups"


def _bounded(value: int, *, minimum: int, maximum: int) -> int:
    return max(minimum, min(int(value), maximum))


def _skill_name_from_text(text: str, fallback: str) -> str:
    match = _FRONTMATTER_NAME_RE.match(text)
    if match:
        name_match = _NAME_RE.search(match.group("body"))
        if name_match:
            return name_match.group("name").strip()
    return fallback


def discover_skill_files(skills_dir: str | Path) -> dict[str, Path]:
    """Return top-level skill names mapped to their SKILL.md files."""

    root = Path(skills_dir)
    if not root.exists():
        return {}
    discovered: dict[str, Path] = {}
    for skill_file in sorted(root.rglob("SKILL.md")):
        if "/.archive/" in str(skill_file) or "/.curator_backups/" in str(skill_file):
            continue
        try:
            text = skill_file.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        name = _skill_name_from_text(text, skill_file.parent.name)
        discovered[name] = skill_file
    return discovered


def _format_evidence_rows(evidence_rows: list[dict[str, Any]], *, limit: int = 5) -> list[str]:
    lines: list[str] = []
    for row in evidence_rows[:limit]:
        marker = "error" if row.get("is_error") else "ok"
        preview = str(row.get("result_preview") or "").replace("\n", " ").strip()
        if len(preview) > 220:
            preview = preview[:219] + "…"
        created = row.get("created_at") or "unknown-time"
        tool = row.get("tool_name") or "unknown-tool"
        suffix = f" — {preview}" if preview else ""
        lines.append(f"- {created}: `{tool}` {marker}{suffix}")
    return lines


def _managed_block(
    *,
    skill_name: str,
    days: int,
    summary: dict[str, Any],
    evidence_rows: list[dict[str, Any]],
) -> str:
    generated_at = datetime.now(timezone.utc).isoformat(timespec="seconds")
    evidence_lines = _format_evidence_rows(evidence_rows)
    if not evidence_lines:
        evidence_lines = ["- No individual evidence rows were available; aggregate counts triggered this pass."]
    return "\n".join(
        [
            _START,
            "## Auto-curated evidence notes",
            "",
            "Low-risk append-only auto-curation generated by `hermes-curator-evolver`.",
            "These notes are evidence summaries for future agents; they do not replace human-authored SOPs.",
            "",
            f"- Skill: `{skill_name}`",
            f"- Generated at: `{generated_at}`",
            f"- Evidence window: last {days} day(s)",
            f"- Tool events: {int(summary.get('tool_events') or 0)}",
            f"- Skill events: {int(summary.get('skill_events') or 0)}",
            f"- Error-like events: {int(summary.get('error_events') or 0)}",
            "",
            "### Recent evidence",
            *evidence_lines,
            "",
            "### Agent guidance",
            "- When this skill is relevant, check these observed signals before choosing a workflow.",
            "- Prefer targeted verification over broad retries when similar errors recur.",
            "- If a repeated issue is understood, replace this evidence note with a concise human-readable SOP update.",
            _END,
            "",
        ]
    )


def build_low_risk_skill_update(
    *,
    skill_name: str,
    skill_text: str,
    days: int,
    summary: dict[str, Any],
    evidence_rows: list[dict[str, Any]],
) -> str:
    """Return an append-only managed update that preserves existing skill text."""

    block = _managed_block(
        skill_name=skill_name,
        days=days,
        summary=summary,
        evidence_rows=evidence_rows,
    )
    if _START in skill_text and _END in skill_text:
        pattern = re.compile(re.escape(_START) + r".*?" + re.escape(_END) + r"\n?", re.DOTALL)
        return pattern.sub(block, skill_text, count=1)
    separator = "\n" if skill_text.endswith("\n") else "\n\n"
    return skill_text + separator + block


def _candidate_skill_names(report: dict[str, Any], *, max_skills: int, min_evidence: int) -> list[str]:
    names: list[str] = []
    for row in report.get("summary", {}).get("skills", []) or []:
        count = int(row.get("event_count") or 0)
        name = row.get("skill_name")
        if name and count >= min_evidence:
            names.append(str(name))
        if len(names) >= max_skills:
            break
    return names


def run_auto_evolve(config: AutoEvolveConfig | None = None) -> dict[str, Any]:
    """Run one automatic skill evolution pass.

    By default this is a dry-run. Actual writes require both `apply_low_risk` and
    `approve_auto_apply`; even then, writes are append-only and go through
    guarded apply.
    """

    cfg = config or AutoEvolveConfig()
    days = _bounded(cfg.days, minimum=1, maximum=3650)
    max_skills = _bounded(cfg.max_skills, minimum=1, maximum=25)
    min_evidence = _bounded(cfg.min_evidence, minimum=1, maximum=1000)
    skills_dir = Path(cfg.skills_dir) if cfg.skills_dir is not None else _default_skills_dir()
    backup_dir = Path(cfg.backup_dir) if cfg.backup_dir is not None else _default_backup_dir()
    store = EvidenceStore(cfg.db_path)
    report = build_report(store, days=days)
    skill_files = discover_skill_files(skills_dir)
    names = _candidate_skill_names(report, max_skills=max_skills, min_evidence=min_evidence)
    mode = "apply-low-risk" if cfg.apply_low_risk else "dry-run"
    candidates: list[dict[str, Any]] = []
    applied = 0

    for name in names:
        skill_file = skill_files.get(name)
        candidate: dict[str, Any] = {
            "skill_name": name,
            "risk": "low",
            "mutation_policy": "append-only-managed-block",
            "target_path": str(skill_file) if skill_file else None,
        }
        if not skill_file:
            candidate["status"] = "skipped"
            candidate["reason"] = "skill-file-not-found"
            candidates.append(candidate)
            continue
        skill_report = build_report(store, days=days, skill=name)
        skill_summary = skill_report.get("summary") or {}
        evidence_rows = skill_report.get("skill_evidence") or []
        original = skill_file.read_text(encoding="utf-8")
        updated = build_low_risk_skill_update(
            skill_name=name,
            skill_text=original,
            days=days,
            summary=skill_summary,
            evidence_rows=evidence_rows,
        )
        candidate.update(
            {
                "status": "planned",
                "current_sha256": sha256_file(skill_file),
                "new_content_changed": updated != original,
                "evidence_summary": {
                    "tool_events": int(skill_summary.get("tool_events") or 0),
                    "skill_events": int(skill_summary.get("skill_events") or 0),
                    "error_events": int(skill_summary.get("error_events") or 0),
                },
            }
        )
        if cfg.apply_low_risk:
            if not cfg.approve_auto_apply:
                candidate["apply_result"] = {
                    "applied": False,
                    "reason": "auto-approval-required",
                }
            else:
                apply_result = apply_guarded_patch(
                    target_path=skill_file,
                    new_content=updated,
                    expected_sha256=candidate["current_sha256"],
                    approved=True,
                    backup_root=backup_dir,
                    verify_command=cfg.verify_command,
                    verify_cwd=cfg.verify_cwd or skills_dir,
                )
                candidate["apply_result"] = apply_result
                if apply_result.get("applied"):
                    applied += 1
                    candidate["status"] = "applied"
        candidates.append(candidate)

    return {
        "schema_version": "0.6",
        "mode": mode,
        "safety": {
            "core_modifications": False,
            "writes_require_apply_low_risk": True,
            "writes_require_auto_approval": True,
            "mutation_policy": "append-only managed block + guarded apply backup/rollback",
        },
        "config": {
            "db_path": str(store.db_path),
            "skills_dir": str(skills_dir),
            "backup_dir": str(backup_dir),
            "days": days,
            "max_skills": max_skills,
            "min_evidence": min_evidence,
        },
        "summary": {
            "planned": len([c for c in candidates if c.get("status") in {"planned", "applied"}]),
            "applied": applied,
            "skipped": len([c for c in candidates if c.get("status") == "skipped"]),
        },
        "candidates": candidates,
    }


def _systemd_dir() -> Path:
    return Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")) / "systemd" / "user"


def install_auto_timer(
    *,
    schedule: str = "daily",
    skills_dir: str | Path | None = None,
    apply_low_risk: bool = True,
    enable: bool = False,
) -> dict[str, Any]:
    """Install a user systemd timer for automatic evolution.

    The timer is disabled unless `enable=True`, so package install can stay
    non-invasive while still providing a one-command plug-in automation path.
    """

    unit_dir = _systemd_dir()
    unit_dir.mkdir(parents=True, exist_ok=True)
    service_path = unit_dir / "hermes-curator-evolver-auto.service"
    timer_path = unit_dir / "hermes-curator-evolver-auto.timer"
    target_skills = Path(skills_dir) if skills_dir is not None else _default_skills_dir()
    on_calendar = {"hourly": "hourly", "daily": "daily", "weekly": "weekly"}.get(schedule, schedule)
    args = [
        sys.executable,
        "-m",
        "hermes_curator_evolver",
        "auto-run",
        "--skills-dir",
        str(target_skills),
        "--format",
        "json",
    ]
    if apply_low_risk:
        args.extend(["--apply-low-risk", "--approve-auto-apply"])
    command = " ".join(args)
    service_path.write_text(
        "\n".join(
            [
                "[Unit]",
                "Description=Hermes Curator Evolver automatic low-risk skill evolution",
                "",
                "[Service]",
                "Type=oneshot",
                f"ExecStart={command}",
                "",
            ]
        ),
        encoding="utf-8",
    )
    timer_path.write_text(
        "\n".join(
            [
                "[Unit]",
                "Description=Run Hermes Curator Evolver automatic skill evolution",
                "",
                "[Timer]",
                f"OnCalendar={on_calendar}",
                "Persistent=true",
                "",
                "[Install]",
                "WantedBy=timers.target",
                "",
            ]
        ),
        encoding="utf-8",
    )
    result = {
        "installed": True,
        "enabled": False,
        "service_path": str(service_path),
        "timer_path": str(timer_path),
        "schedule": on_calendar,
        "command": command,
    }
    if enable:
        import subprocess

        completed = subprocess.run(
            ["systemctl", "--user", "enable", "--now", timer_path.name],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            check=False,
        )
        result["enabled"] = completed.returncode == 0
        result["systemctl"] = {"exit_code": completed.returncode, "output": completed.stdout[-2000:]}
    return result


def uninstall_auto_timer(*, disable: bool = True) -> dict[str, Any]:
    """Remove the user systemd timer/service installed by this plugin."""

    unit_dir = _systemd_dir()
    service_path = unit_dir / "hermes-curator-evolver-auto.service"
    timer_path = unit_dir / "hermes-curator-evolver-auto.timer"
    result: dict[str, Any] = {"removed": [], "missing": []}
    if disable:
        import subprocess

        completed = subprocess.run(
            ["systemctl", "--user", "disable", "--now", timer_path.name],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            check=False,
        )
        result["systemctl"] = {"exit_code": completed.returncode, "output": completed.stdout[-2000:]}
    for path in (timer_path, service_path):
        if path.exists():
            path.unlink()
            result["removed"].append(str(path))
        else:
            result["missing"].append(str(path))
    return result


def format_auto_evolve_result(result: dict[str, Any], *, output_format: str) -> str:
    if output_format == "json":
        return json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True)
    lines = [
        "# Hermes Curator Evolver Auto Run",
        "",
        f"- Mode: `{result['mode']}`",
        f"- Planned: {result['summary']['planned']}",
        f"- Applied: {result['summary']['applied']}",
        f"- Skipped: {result['summary']['skipped']}",
        "",
        "## Candidates",
        "",
    ]
    for candidate in result.get("candidates") or []:
        lines.append(
            f"- `{candidate.get('skill_name')}` — {candidate.get('status')} ({candidate.get('risk')})"
        )
        if candidate.get("apply_result"):
            lines.append(f"  - apply: {candidate['apply_result'].get('reason')}")
    if not result.get("candidates"):
        lines.append("- No skills met the evidence threshold.")
    return "\n".join(lines)
